/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musicmanagerapp;

/**
 *
 * @author dmoc2
 */
public class PlaylistGUI extends javax.swing.JFrame {

    /**
     * Creates new form PlaylistGUI
     */
    
    PlaylistLinearInterface load;
     PlaylistLinearInterface load1;
    public PlaylistGUI() {
        initComponents();
        load = new PopRapDDL();
        load1 = new IndieRockDDL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPane = new javax.swing.JPanel();
        border = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        layeredHeadPane = new javax.swing.JLayeredPane();
        HeaderPane3 = new javax.swing.JPanel();
        LikeLogo2 = new javax.swing.JLabel();
        LikedSongsLabel2 = new javax.swing.JLabel();
        PopRapPanel = new javax.swing.JPanel();
        HeaderPane2 = new javax.swing.JPanel();
        LikeLogo1 = new javax.swing.JLabel();
        LikedSongsLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayPopSongs = new javax.swing.JTextArea();
        searchPlaylistOne = new javax.swing.JTextField();
        searchBTN1 = new javax.swing.JButton();
        deleteBTN1 = new javax.swing.JButton();
        displayBTN1 = new javax.swing.JButton();
        shuffle = new javax.swing.JButton();
        addSongsBTN = new javax.swing.JButton();
        IndieRockPanel = new javax.swing.JPanel();
        HeaderPane1 = new javax.swing.JPanel();
        LikeLogo = new javax.swing.JLabel();
        LikedSongsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayPlaylist2 = new javax.swing.JTextArea();
        searchPlaylist2 = new javax.swing.JTextField();
        searchPlaylist2BTN = new javax.swing.JButton();
        deletePlaylist2BTN = new javax.swing.JButton();
        displayPlaylist2BTN = new javax.swing.JButton();
        addSongsBTN1 = new javax.swing.JButton();
        shuffle1 = new javax.swing.JButton();
        StringifyLogo = new javax.swing.JLabel();
        HeadingText = new javax.swing.JLabel();

        HeaderPane.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout HeaderPaneLayout = new javax.swing.GroupLayout(HeaderPane);
        HeaderPane.setLayout(HeaderPaneLayout);
        HeaderPaneLayout.setHorizontalGroup(
            HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        HeaderPaneLayout.setVerticalGroup(
            HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        border.setBackground(new java.awt.Color(0, 0, 0));

        body.setBackground(new java.awt.Color(0, 0, 0));

        layeredHeadPane.setBackground(new java.awt.Color(153, 204, 255));

        HeaderPane3.setBackground(new java.awt.Color(0, 204, 204));

        LikeLogo2.setBackground(new java.awt.Color(153, 204, 255));
        LikeLogo2.setForeground(new java.awt.Color(255, 255, 255));
        LikeLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LikeLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/loveHeartLogo.png"))); // NOI18N

        LikedSongsLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        LikedSongsLabel2.setText("PlayList 1 | Enjoy your songs in one list!");

        javax.swing.GroupLayout HeaderPane3Layout = new javax.swing.GroupLayout(HeaderPane3);
        HeaderPane3.setLayout(HeaderPane3Layout);
        HeaderPane3Layout.setHorizontalGroup(
            HeaderPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LikeLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LikedSongsLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderPane3Layout.setVerticalGroup(
            HeaderPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPane3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(HeaderPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LikeLogo2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LikedSongsLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layeredHeadPane.setLayer(HeaderPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredHeadPaneLayout = new javax.swing.GroupLayout(layeredHeadPane);
        layeredHeadPane.setLayout(layeredHeadPaneLayout);
        layeredHeadPaneLayout.setHorizontalGroup(
            layeredHeadPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredHeadPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layeredHeadPaneLayout.setVerticalGroup(
            layeredHeadPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        HeaderPane2.setBackground(new java.awt.Color(0, 204, 204));

        LikeLogo1.setBackground(new java.awt.Color(153, 204, 255));
        LikeLogo1.setForeground(new java.awt.Color(255, 255, 255));
        LikeLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LikeLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/loveHeartLogo.png"))); // NOI18N

        LikedSongsLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        LikedSongsLabel1.setText("Liked Songs |   View all of your favourite Songs ");

        javax.swing.GroupLayout HeaderPane2Layout = new javax.swing.GroupLayout(HeaderPane2);
        HeaderPane2.setLayout(HeaderPane2Layout);
        HeaderPane2Layout.setHorizontalGroup(
            HeaderPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LikeLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LikedSongsLabel1)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        HeaderPane2Layout.setVerticalGroup(
            HeaderPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(HeaderPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LikeLogo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LikedSongsLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        displayPopSongs.setColumns(20);
        displayPopSongs.setRows(5);
        displayPopSongs.setText("Title \t Artist \t Album \t Genre \n");
        jScrollPane2.setViewportView(displayPopSongs);

        searchPlaylistOne.setToolTipText("Enter the song name to complete the search");

        searchBTN1.setBackground(new java.awt.Color(102, 102, 102));
        searchBTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/searchIcon.png"))); // NOI18N
        searchBTN1.setToolTipText("Enter into the searchterm field and press me");
        searchBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTN1ActionPerformed(evt);
            }
        });

        deleteBTN1.setBackground(new java.awt.Color(255, 102, 102));
        deleteBTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/binIcon.png"))); // NOI18N
        deleteBTN1.setToolTipText("Removes the recently added song!");
        deleteBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTN1ActionPerformed(evt);
            }
        });

        displayBTN1.setText("Display");
        displayBTN1.setToolTipText("Press me to refresh the liked songs after searching");
        displayBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTN1ActionPerformed(evt);
            }
        });

        shuffle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/shuffify.png"))); // NOI18N
        shuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuffleActionPerformed(evt);
            }
        });

        addSongsBTN.setText("ADD");
        addSongsBTN.setToolTipText("To add new songs press me ");
        addSongsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PopRapPanelLayout = new javax.swing.GroupLayout(PopRapPanel);
        PopRapPanel.setLayout(PopRapPanelLayout);
        PopRapPanelLayout.setHorizontalGroup(
            PopRapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PopRapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PopRapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PopRapPanelLayout.createSequentialGroup()
                        .addComponent(searchPlaylistOne, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBTN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PopRapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(addSongsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PopRapPanelLayout.setVerticalGroup(
            PopRapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopRapPanelLayout.createSequentialGroup()
                .addComponent(HeaderPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PopRapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPlaylistOne, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PopRapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteBTN1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(displayBTN1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(PopRapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopRapPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopRapPanelLayout.createSequentialGroup()
                        .addComponent(addSongsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredHeadPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PopRapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(layeredHeadPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 377, Short.MAX_VALUE))
            .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PopRapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabbedPane.addTab("PlayList 1", homePanel);

        HeaderPane1.setBackground(new java.awt.Color(0, 204, 204));

        LikeLogo.setBackground(new java.awt.Color(153, 204, 255));
        LikeLogo.setForeground(new java.awt.Color(255, 255, 255));
        LikeLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LikeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/loveHeartLogo.png"))); // NOI18N

        LikedSongsLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        LikedSongsLabel.setText("PlayList 2 | Enjoy your songs in one list!");

        javax.swing.GroupLayout HeaderPane1Layout = new javax.swing.GroupLayout(HeaderPane1);
        HeaderPane1.setLayout(HeaderPane1Layout);
        HeaderPane1Layout.setHorizontalGroup(
            HeaderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LikeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LikedSongsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderPane1Layout.setVerticalGroup(
            HeaderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(HeaderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LikeLogo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LikedSongsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        displayPlaylist2.setColumns(20);
        displayPlaylist2.setRows(5);
        displayPlaylist2.setText("Title \t Artist \t Album \t Genre \n");
        jScrollPane1.setViewportView(displayPlaylist2);

        searchPlaylist2.setToolTipText("Enter the song name to complete the search");

        searchPlaylist2BTN.setBackground(new java.awt.Color(102, 102, 102));
        searchPlaylist2BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/searchIcon.png"))); // NOI18N
        searchPlaylist2BTN.setToolTipText("Enter into the searchterm field and press me");
        searchPlaylist2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPlaylist2BTNActionPerformed(evt);
            }
        });

        deletePlaylist2BTN.setBackground(new java.awt.Color(255, 102, 102));
        deletePlaylist2BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/binIcon.png"))); // NOI18N
        deletePlaylist2BTN.setToolTipText("Press me to delete the most recent song");
        deletePlaylist2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlaylist2BTNActionPerformed(evt);
            }
        });

        displayPlaylist2BTN.setText("Display");
        displayPlaylist2BTN.setToolTipText("Press me to refresh the liked songs after searching");
        displayPlaylist2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPlaylist2BTNActionPerformed(evt);
            }
        });

        addSongsBTN1.setText("ADD");
        addSongsBTN1.setToolTipText("To add new songs press me ");
        addSongsBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongsBTN1ActionPerformed(evt);
            }
        });

        shuffle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/shuffify.png"))); // NOI18N
        shuffle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuffle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IndieRockPanelLayout = new javax.swing.GroupLayout(IndieRockPanel);
        IndieRockPanel.setLayout(IndieRockPanelLayout);
        IndieRockPanelLayout.setHorizontalGroup(
            IndieRockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(IndieRockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IndieRockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(IndieRockPanelLayout.createSequentialGroup()
                        .addComponent(searchPlaylist2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchPlaylist2BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPlaylist2BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IndieRockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletePlaylist2BTN, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(addSongsBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shuffle1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        IndieRockPanelLayout.setVerticalGroup(
            IndieRockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndieRockPanelLayout.createSequentialGroup()
                .addComponent(HeaderPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IndieRockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPlaylist2BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPlaylist2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(IndieRockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deletePlaylist2BTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(displayPlaylist2BTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(IndieRockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IndieRockPanelLayout.createSequentialGroup()
                        .addComponent(addSongsBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shuffle1)))
                .addContainerGap())
        );

        tabbedPane.addTab("PlayList 2", IndieRockPanel);

        StringifyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Stringify.png"))); // NOI18N

        HeadingText.setBackground(new java.awt.Color(255, 255, 255));
        HeadingText.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 35)); // NOI18N
        HeadingText.setForeground(new java.awt.Color(255, 255, 255));
        HeadingText.setText("Stringify");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StringifyLogo)
                .addGap(18, 18, 18)
                .addComponent(HeadingText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StringifyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeadingText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(border, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchPlaylist2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPlaylist2BTNActionPerformed
        // TODO add your handling code here:
        String songName = searchPlaylist2.getText();
        load1.Search(songName);
    }//GEN-LAST:event_searchPlaylist2BTNActionPerformed

    private void deletePlaylist2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlaylist2BTNActionPerformed
        // TODO add your handling code here:
       load1.remove(evt);
    }//GEN-LAST:event_deletePlaylist2BTNActionPerformed

    private void displayPlaylist2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPlaylist2BTNActionPerformed
            load1.displayForward();
    }//GEN-LAST:event_displayPlaylist2BTNActionPerformed

    private void searchBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTN1ActionPerformed
        // TODO add your handling code here:
        load.Search(searchPlaylistOne.getText());
        String songName = searchPlaylistOne.getText();
        load.displaySearch(songName);
    }//GEN-LAST:event_searchBTN1ActionPerformed

    private void deleteBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTN1ActionPerformed
        // TODO add your handling code here:
         String songName = searchPlaylistOne.getText();
        load.remove(songName);
    }//GEN-LAST:event_deleteBTN1ActionPerformed

    private void displayBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTN1ActionPerformed
        // TODO add your handling code here:
        load.displayForward();
    }//GEN-LAST:event_displayBTN1ActionPerformed

    private void shuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuffleActionPerformed
        // TODO add your handling code here:
        load.displayBackward();
    }//GEN-LAST:event_shuffleActionPerformed

    private void addSongsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongsBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_addSongsBTNActionPerformed

    private void shuffle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuffle1ActionPerformed
        // TODO add your handling code here:
        load1.displayBackward();
    }//GEN-LAST:event_shuffle1ActionPerformed

    private void addSongsBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongsBTN1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_addSongsBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPane;
    private javax.swing.JPanel HeaderPane1;
    private javax.swing.JPanel HeaderPane2;
    private javax.swing.JPanel HeaderPane3;
    private javax.swing.JLabel HeadingText;
    private static javax.swing.JPanel IndieRockPanel;
    private javax.swing.JLabel LikeLogo;
    private javax.swing.JLabel LikeLogo1;
    private javax.swing.JLabel LikeLogo2;
    private javax.swing.JLabel LikedSongsLabel;
    private javax.swing.JLabel LikedSongsLabel1;
    private javax.swing.JLabel LikedSongsLabel2;
    private static javax.swing.JPanel PopRapPanel;
    private javax.swing.JLabel StringifyLogo;
    private javax.swing.JButton addSongsBTN;
    private javax.swing.JButton addSongsBTN1;
    private javax.swing.JPanel body;
    private javax.swing.JPanel border;
    private javax.swing.JButton deleteBTN1;
    private javax.swing.JButton deletePlaylist2BTN;
    private javax.swing.JButton displayBTN1;
    public static javax.swing.JTextArea displayPlaylist2;
    private javax.swing.JButton displayPlaylist2BTN;
    public static javax.swing.JTextArea displayPopSongs;
    private javax.swing.JPanel homePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLayeredPane layeredHeadPane;
    private javax.swing.JButton searchBTN1;
    public static javax.swing.JTextField searchPlaylist2;
    private javax.swing.JButton searchPlaylist2BTN;
    public static javax.swing.JTextField searchPlaylistOne;
    private javax.swing.JButton shuffle;
    private javax.swing.JButton shuffle1;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
